"""add speakers table and speaker_id to sessions

Revision ID: 1d999ebdd174
Revises: 9df2ba4f4e20
Create Date: 2026-06-07 21:29:02.125204

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d999ebdd174'
down_revision: Union[str, Sequence[str], None] = '9df2ba4f4e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speakers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event_sessions', sa.Column('speaker_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'event_sessions', 'speakers', ['speaker_id'], ['id'])
    op.drop_column('event_sessions', 'speaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sessions', sa.Column('speaker', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_sessions', type_='foreignkey')
    op.drop_column('event_sessions', 'speaker_id')
    op.drop_table('speakers')
    # ### end Alembic commands ###
