"""add end_date to events

Revision ID: b7095e8d17de
Revises: 23f6b8853ac3
Create Date: 2026-06-07 15:35:46.687382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7095e8d17de'
down_revision: Union[str, Sequence[str], None] = '23f6b8853ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'end_date')
    # ### end Alembic commands ###
